---
version: '3'
services:

# START SERVICE metricbeat.overlay
  metricbeat:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.metricbeat.overlay:7.8.0
    environment: ['ES_METRICBEAT_OUTPUT_CONSOLE=${METRICS_OVERLAY_ENVIRONMENT_OUTPUT_CONSOLE}','ES_METRICBEAT_OUTPUT_ELASTICSEARCH=${METRICS_OVERLAY_ENVIRONMENT_OUTPUT_ELASTICSEARCH}','ES_METRICBEAT_OUTPUT_KAFKA=${METRICS_OVERLAY_ENVIRONMENT_OUTPUT_KAFKA}','ES_METRICBEAT_OUTPUT_CONFIG_ELASTICSEARCH_HOSTS=${METRICS_OVERLAY_ENVIRONMENT_OUTPUT_CONFIG_ELASTICSEARCH_HOSTS}','ES_METRICBEAT_OUTPUT_CONFIG_KIBANA_HOST=${METRICS_OVERLAY_ENVIRONMENT_OUTPUT_CONFIG_KIBANA_HOST}','ES_METRICBEAT_OUTPUT_CONFIG_KIBANA_DASHBOARDS=${METRICS_OVERLAY_ENVIRONMENT_OUTPUT_CONFIG_KIBANA_DASHBOARDS}','ES_METRICBEAT_OUTPUT_CONFIG_KAFKA_HOSTS=${METRICS_OVERLAY_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_HOSTS}','ES_METRICBEAT_OUTPUT_CONFIG_KAFKA_TOPIC=${METRICS_OVERLAY_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_TOPIC}',${METRICS_OVERLAY_ENVIRONMENT_SERVICES}]
    command: []
    volumes: ['/etc:/hostfs/etc:ro','${CONTECO_STACKPREFIX}_metrics_overlay_volume:/usr/share/metricbeat/data']
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${METRICS_OVERLAY_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${METRICS_OVERLAY_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${METRICS_OVERLAY_COMPOSE_EXTENSIONS}
# END SERVICE metricbeat.overlay

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_metrics_overlay_volume: { external: true }}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
