#!/usr/bin/env bash


	executionplane --silent docker volume create swarm_g1_ekg_elasticsearch_volume
	
	executionplane --silent docker volume create swarm_g1_ekg_grafana_volume
	
	executionplane --silent docker volume create swarm_g1_ingest_container_logs_filebeat_volume
	
	executionplane --silent docker volume create swarm_g1_ingest_container_settings_filebeat_volume
	
	executionplane --silent docker volume create swarm_g1_ingest_journalctl_filebeat_volume
	
	executionplane --silent docker volume create swarm_g1_kz_kafka_secrets_volume
	
	executionplane --silent docker volume create swarm_g1_kz_kafka_data_volume
	
	executionplane --silent docker volume create swarm_g1_kz_zookeeper_secrets_volume
	
	executionplane --silent docker volume create swarm_g1_kz_zookeeper_data_volume
	
	executionplane --silent docker volume create swarm_g1_kz_zookeeper_log_volume
	
	executionplane --silent docker volume create swarm_g1_metrics_monitor_heartbeat_data_volume
	
	executionplane --silent docker volume create swarm_g1_metrics_monitor_heartbeat_monitors_volume
	
	executionplane --silent docker volume create swarm_g1_metrics_node_metrics_node_volume
	
	executionplane --silent docker volume create swarm_g1_metrics_overlay_metrics_overlay_volume
	
	executionplane --silent docker volume create swarm_g1_export_streamsets_volume
	
	executionplane --silent docker volume create swarm_g1_processor_streamsets_volume
	
executionplane --silent docker run -v swarm_g1_ekg_elasticsearch_volume:/usr/share/elasticsearch/data ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /soleco//_component/_volumes/ekg_elasticsearch_volume.tar
		
executionplane --silent docker run -v swarm_g1_ekg_grafana_volume:/var/lib/grafana ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /soleco//_component/_volumes/ekg_grafana_volume.tar
		
executionplane --silent docker run -v swarm_g1_metrics_monitor_heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${CONTECO_REGISTRY}$1 --interactive cp -r /soleco//_component/_volumes/metrics_monitor_heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d
		
executionplane --silent docker run -v swarm_g1_export_streamsets_volume:/data ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /soleco//_component/_volumes/export_streamsets_volume.tar
		
executionplane --silent docker run -v swarm_g1_processor_streamsets_volume:/data ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /soleco//_component/_volumes/processor_streamsets_volume.tar
		
