#- type: http
#  id: external_ekg_elasticsearch_endpoint
#  name: EKG ElasticSearch External
#  hosts: ["http://"]
#  check.response.status: [200]
#  schedule: '@every 30s'
#  fields:
#    scope: "swarm_g1"
#    stack: ekg
#    type: external
#    service: elasticsearch
#    area: rest_api

- type: http
  id: external_ekg_grafana_endpoint
  name: EKG grafana External
  hosts: ["http://${CONTECO_HOSTNAME}/swarm/ekg/grafana"]
  check.response.status: [301]
  schedule: '@every 30s'
  fields:
    scope: "swarm_g1"
    stack: ekg
    type: external
    service: kibana
    area: endpoint

- type: http
  id: external_ekg_kibana_endpoint
  name: EKG Kibana External
  hosts: ["http://${CONTECO_HOSTNAME}/swarm/ekg/kibana"]
  check.response.status: [301]
  schedule: '@every 30s'
  fields:
    scope: "swarm_g1"
    stack: ekg
    type: external
    service: kibana
    area: endpoint



- type: http
  id: internal_ekg_elasticsearch_endpoint
  name: EKG ElasticSearch Internal
  hosts: ["http://module_swarm_g1_ekg_elasticsearch:9200"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "swarm_g1"
    stack: ekg
    type: internal
    service: elasticsearchhttp://
    area: rest_api

- type: http
  id: internal_ekg_grafana_endpoint
  name: EKG Grafana Internal
  hosts: ["http://module_swarm_g1_ekg_grafana:3000"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "swarm_g1"
    stack: ekg
    type: internal
    service: grafana
    area: endpoint

- type: http
  id: internal_ekg_kibana_endpoint
  name: EKG Kibana Internal
  hosts: ["http://module_swarm_g1_ekg_kibana:5601"]
  check.response.status: [302]
  schedule: '@every 30s'
  fields:
    scope: "swarm_g1"
    stack: ekg
    type: internal
    service: kibana
    area: endpoint
